export const ingredientNameMap: Record<string, string> = {
	eggs: "Яйца",
	sugar: "Сахар",
	bananaPuree: "Банановое пюре",
	milk: "Молоко",
	butter: "Сливочное масло",
	sourCream: "Сметана",
	flour: "Мука",
	starch: "Крахмал",
	bakingSoda: "Сода",
	bakingPowder: "Разрыхлитель",
	creamCheese: "Творожный сыр",
	cream: "Сливки",
	powderedSugar: "Сахарная пудра",
	boiledCondensedMilk: "Варёная сгущенка",
	water: "Вода",
	bananas: "Бананы",
	oil: "Подсолнечное масло",
	apple: "Яблоки",
	applePuree: "Яблочное пюре",
	whiteChocolate: "Белый шоколад",
	carrot: "Морковь",
	orangePeel: "Цедра апельсина",
	salt: "Соль",
	vanillaSugar: "Ванильный сахар",
	lemonJuice: "Сок лимона",
	peanutButter: "Арахисовая паста",
	saltedCaramel: "Соленая карамель",
	peanut: "Арахис",
	strawberry: "Клубника",
	strawberryJam: "Клубничный конфитюр",
	blackChocolate: "Темный шоколад",
	cherry: "Вишня",
	kefir: "Кефир"
};

export const fillerNameMap: Record<string, string> = {
	bananaCaramel: "Банан - Карамель",
	appleCaramel: "Карамельное Яблоко",
	carrot: "Морковь - Апельсин",
	citrus: 'Цитрус',
	snickers: "Сникерс",
	strawberryVanilla: "Клубника - Ваниль",
	cherryChocolate: "Вишня - Шоколад",
	redVelvetCherry: "Красный Бархат (Вишня)",
	redVelvetStrawberry: "Красный Бархат (Клубника)"
};