export const ingredientNameMap: Record<string, string> = {
	eggs: "Яйца",
	sugar: "Сахар",
	bananaPuree: "Банановое пюре",
	milk: "Молоко",
	butter: "Сливочное масло",
	sourCream: "Сметана",
	flour: "Мука",
	starch: "Крахмал",
	bakingSoda: "Сода",
	bakingPowder: "Разрыхлитель",
	creamCheese: "Творожный сыр",
	cream: "Сливки",
	powderedSugar: "Сахарная пудра",
	boiledCondensedMilk: "Варёная сгущенка",
	water: "Вода",
	bananas: "Бананы",
	oil: "Подсолнечное масло",
	apple: "Яблоки"
};